[platformio]
default_envs = ai_thinker
extra_configs = secrets.ini

[env:ai_thinker]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = huge_app.csv
extra_scripts = pre:scripts/generate_secrets.py
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  knolleary/PubSubClient@^2.8
